### ISSUE TITLE
Approval layout incorrect

### ISSUE THREAD

**Issue by amcpherson** [rchurchley/sfuthesis#16]
From the library staff:

Chair section should be:

    chair: Dr. Joe Jones
           Professor

Instead of:
    
    Dr. Joe Jones (chair)
    Professor

Also, it would be nice if the title did not hyphenate on the approval page, not sure how to fix this.

(I am not sure how interested you are in tweaking the template to produce the correct layout for the approval page, up to you of course)

**Comment by amcpherson** [comment]
Have a fix for this, will do a pull request.

**Comment by rchurchley** [comment]
Thanks for the report! I would welcome a pull request. I imagine you put the chair in a table?

> Also, it would be nice if the title did not hyphenate on the approval page, not sure how to fix this.

After reading this [StackExchange question](http://tex.stackexchange.com/questions/91307/temporarily-suppress-hyphenation), I believe the answer is to set `\language=\l@nohyphenation` either inside the title or inside the definition of `\@approvalvalue`. Could you test this solution with your thesis and make sure it does not have any adverse effects on the main text?

> (I am not sure how interested you are in tweaking the template to produce the correct layout for the approval page, up to you of course)

If anything needs to be tweaked or could be improved, I definitely want to fix it!

**Comment by amcpherson** [comment]
Added a pull request.  Saw your message too late.  Ended up using \raggedright to deal with hyphenation issue and it works fine.
