### ISSUE TITLE
Labels not being referenced

### ISSUE THREAD

**Issue by fcastilloec** [rchurchley/sfuthesis#21]
While using the sfuthesis class, and using \label and \ref or \autoref, the output of this references on the pdf is empty. A simple example code follows:
```
\chapter{Introduction}
\label{ch:intro}
By default, only works cited in the text will be added to the bibliography

\chapter{Second}
The same as what we find in \autoref{ch:intro}
```
This outputs a black reference, in this case only the word `Chapter`

After looking at the class file, and some trial and error, the following lines are the cupable for this error:
```
\pretocmd{\@chapter}{\begingroup\smallspacing}{}{}
\apptocmd{\@chapter}{\endgroup}{}{}
\pretocmd{\@schapter}{\begingroup\smallspacing}{}{}
\apptocmd{\@schapter}{\endgroup}{}{}
\pretocmd{\@sect}{\begingroup\smallspacing}{}{}
\apptocmd{\@sect}{\endgroup}{}{}
\pretocmd{\@ssect}{\begingroup\smallspacing}{}{}
\apptocmd{\@ssect}{\endgroup}{}{}
```
I'm an intermediate LaTex user, so I'm not really sure what these lines do or how to fix them. I would appreciate if you can take a quick look at them.

**EDIT:** After more trial and error and asking online, I figure out that the problem is `\label` has to placed between the `\begingroup` and `\endgroup` commands, in other words, right after the `\chapter`, etc.
A workaround suggested says that labels should be placed like this:

`\chapter{Introduction \label{ch:intro}}`

But I think it should be better if the class itself is fixed rather than having to change the way we label sections.

**Comment by rchurchley** [comment]
Thank you for the bug report and thorough research! I agree that this is something that needs to be addressed in the class.

Now that you bring it up, I'm concerned that my use of `\begingroup` and `\endgroup` there was more dangerous than I originally thought. The original intent was to scope the \smallspacing to just the chapter and section titles. However, as you discovered, that will limit the scope of anything else that lives inside. This has the potential to have complicated interactions with packages that might redefine `\@chapter` and `\@sect`. I'd like to avoid this, if at all possible, so maybe the best course of action is to find a way to change the spacing for chapter and section titles without using `\begingroup` and `\endgroup`. I'll have to give this some thought.

**Comment by fcastilloec** [comment]
In the meantime, do you think that the pull request I submitted can be a temporary solution? I'd like to use that solution in my writing since using the workaround described here might make it harder to fix once you issue a final fix. What do you think?

**Comment by rchurchley** [comment]
Yes, feel free to use the version of the class from your pull request; I'll merge your change in in for the time being. Hopefully I'll get a chance to investigate and address the problem more fully this weekend or next!

**Comment by rchurchley** [comment]
By the way, I'm leaning towards a solution that would replace the problem code with something along these lines:
```latex
\pretocmd{\@chapter}{\smallspacing}{}{}
\apptocmd{\@chapter}{\defaultspacing}{}{}
...
```
I think that would achieve the correct title spacing while avoiding the problem you reported. If it isn't too much trouble, would you be willing to test this out as well?

**Comment by fcastilloec** [comment]
Sure, I'll try it as soon as possible and let you know

**Comment by rchurchley** [comment]
Sorry for the delay! After some consideration, I believe that the solution I suggested above will be the safest overall solution. (It comes from the first suggestion in [this StackExchange answer](https://tex.stackexchange.com/a/106469).) It required another small tweak to ensure the correct spacing around section titles (especially in the appendix) but appears to solve the problem you reported.

Thanks again for your bug report and your hard work in tracking down the source of the problem! Please let me know if you run into any more difficulties :)

**Comment by fcastilloec** [comment]
Thanks so much for your work! If I find anything else I will definitely let you know
