### ISSUE TITLE
approval page, signing lines

### ISSUE THREAD

**Issue by craigmillernz** [rchurchley/sfuthesis#23]
When I compile my thesis with \documentclass{sfuthesis} the approval page doesn't have a line drawn against each name for signing on.  When I compile it with \documentclass{sfuapproval} I do get the signing lines.  Should the lines appear on the approval page when using the sfuthesis class as well?

**Comment by craigmillernz** [comment]
my mistake, texpath issue...

**Comment by rchurchley** [comment]
At the start of 2017, the library updated the preferred style of the approval page included in the thesis. My understanding is that they no longer want signature lines in the copy of your thesis that gets uploaded to their website. This is why the current version of `sfuthesis` is missing signature lines.

However, for paperwork purposes, you still need to provide your department with a loose-leaf approval page (with signature lines) to be signed at your defence. The purpose of `sfuapproval` is to generate this page.

Hope this helps!

**Comment by craigmillernz** [comment]
Thanks Ross, yes that's correct.  I found that out after talking with the library.   Might be useful to add a note in the readme about this as it is a bit confusing at first.
