### ISSUE TITLE
Approval signature page missing page number

### ISSUE THREAD

**Issue by stefanhannie** [rchurchley/sfuthesis#25]
Hi Ross!

As per [SFU library guidelines](https://www.lib.sfu.ca/help/publish/thesis/format/approval-page) "Both signed and unsigned Approval pages must be numbered page ii." Thought I would forward this requirement along if you've got the time to implement a fix for those that use it in the future.

**Comment by rchurchley** [comment]
Fixed this in c1cd9b39305173dd4fdcdb77a6b786012052c52a.
